name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: vuepress-deploy
        runs: npm install && npm run docs:build
        env:
          TARGET_REPO: tangyuewei/tangyuewei.github.io
          TARGET_BRANCH: master
          BUILD_DIR: docs/.vuepress/dist/
