name: 'auto deploy'
on:
  push:
    branches-ignore:
      - 'production'
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.travis.yml'
      - '.gitignore'
      - '.gitattributes'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - 'dockerfile'
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build
      - name: Deploy to gh-pages
        uses: tangyuewei/rdarida_simple-github-pages-deploy-action@v1
        with:
          git-user: 'tangyuewei'
          git-email: '472680811@qq.com'
          git-base-folder: '_site'
          commit-message: 'deploy'
          branch: 'gh-pages'