name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: vuepress-deploy
      uses: tangyuewei/tangyuewei.github.io@gh_pages
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/
